//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TYM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TYM.Properties.Messages - Copy", typeof(Messages___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the image file. Also supports web links. (DANGER: USE WEB LINKS AT YOUR OWN RISK!).
        /// </summary>
        internal static string Args_FilePath {
            get {
                return ResourceManager.GetString("Args.FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output height as pixels. 1 char height = 2 pixels. Set to 0 for auto size..
        /// </summary>
        internal static string Args_Height {
            get {
                return ResourceManager.GetString("Args.Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List available resampling algorithms..
        /// </summary>
        internal static string Args_ListResamplers {
            get {
                return ResourceManager.GetString("Args.ListResamplers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left margin size as characters. Shifts the output from cursor start to right by specified character count. 1 char width = 1 pixel..
        /// </summary>
        internal static string Args_MarginX {
            get {
                return ResourceManager.GetString("Args.MarginX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top margin size as characters. Shifts the output from cursor start to bottom by specified character count. 1 char height = 2 pixels..
        /// </summary>
        internal static string Args_MarginY {
            get {
                return ResourceManager.GetString("Args.MarginY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resampling algorithm for downsizing..
        /// </summary>
        internal static string Args_ResamplerName {
            get {
                return ResourceManager.GetString("Args.ResamplerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizing mode. Available options: Contain, Cover (Crop), Stretch.
        /// </summary>
        internal static string Args_ResizeMethod {
            get {
                return ResourceManager.GetString("Args.ResizeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use fullscreen. This overrides margin and size arguments!.
        /// </summary>
        internal static string Args_UseFullscreen {
            get {
                return ResourceManager.GetString("Args.UseFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output width as pixels. 1 char width = 1 pixel. Set to 0 for auto size..
        /// </summary>
        internal static string Args_Width {
            get {
                return ResourceManager.GetString("Args.Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the specified file!.
        /// </summary>
        internal static string Error_FileError {
            get {
                return ResourceManager.GetString("Error.FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server returned invalid mime type &quot;%s&quot;!.
        /// </summary>
        internal static string Error_InvalidMimeType {
            get {
                return ResourceManager.GetString("Error.InvalidMimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid resampler specified!.
        /// </summary>
        internal static string Error_InvalidResampler {
            get {
                return ResourceManager.GetString("Error.InvalidResampler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid resize mode specified!.
        /// </summary>
        internal static string Error_InvalidResizeMode {
            get {
                return ResourceManager.GetString("Error.InvalidResizeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch resampler!.
        /// </summary>
        internal static string Error_ResamplerError {
            get {
                return ResourceManager.GetString("Error.ResamplerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server returned code %1!.
        /// </summary>
        internal static string Error_ResponseCode {
            get {
                return ResourceManager.GetString("Error.ResponseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only HTTPS protocol is supported!.
        /// </summary>
        internal static string Error_UnsupportedProtocol {
            get {
                return ResourceManager.GetString("Error.UnsupportedProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse the specified URL!.
        /// </summary>
        internal static string Error_URLParseError {
            get {
                return ResourceManager.GetString("Error.URLParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string LogCategory_Error {
            get {
                return ResourceManager.GetString("LogCategory.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO.
        /// </summary>
        internal static string LogCategory_Info {
            get {
                return ResourceManager.GetString("LogCategory.Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        internal static string LogCategory_Warning {
            get {
                return ResourceManager.GetString("LogCategory.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available resampling algorithms:.
        /// </summary>
        internal static string Message_AvailableResamplers {
            get {
                return ResourceManager.GetString("Message.AvailableResamplers", resourceCulture);
            }
        }
    }
}
