name: Debug

on:
    push:
        branches:
            - dev

jobs:
    debug-build:
        name: Debug build
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: windows-latest
                      target: win

                    - os: ubuntu-latest
                      target: linux

                    - os: macos-latest
                      target: osx

        steps:
            - uses: actions/checkout@v3

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '7.0.x'

            - name: Build
              run: dotnet build src/TYM.csproj

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                name: debug-${{ matrix.target }}
                path: src/bin/