name: Release

on:
    push:
        branches:
            - main
            - dev

jobs:
    draft-release:
        name: Draft new release
        runs-on: ubuntu-latest

        steps:
    
            - name: Fetch source code
              uses: actions/checkout@v3

            - name: Install XML tools
              run: sudo apt install xmlstarlet
              
            - name: Fetch version string
              run: echo "TAG=$(xmlstarlet select --template --value-of /Project/PropertyGroup/AssemblyVersion ./src/TYM.csproj)" >> $GITHUB_OUTPUT
              id: project_version

            - name: Draft release
              uses: softprops/action-gh-release@v1
              id: draft
              env:
                GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
              with:
                tag_name: ${{ steps.project_version.outputs.TAG }}
                name: TYM v${{ steps.project_version.outputs.TAG }}
                draft: true
                prerelease: false
                body_path: CHANGELOG.md


    build-artifacts:
        name: Build release assets
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: windows-latest
                      target: win
                      asset-path: TYM.exe

                    - os: ubuntu-latest
                      target: linux
                      asset-path: TYM

                    - os: macos-latest
                      target: osx
                      asset-path: TYM

        steps:
            
            - name: Fetch source code
              uses: actions/checkout@v3

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '7.0.x'

            - name: Build
              run: dotnet build src/TYM.csproj

            - name: Publish
              run:  dotnet publish src/TYM.csproj -a x64 --os ${{ matrix.target }} -c Release -p:PublishProfile=Properties/PublishProfiles/PublishConfig.pubxml

            - name: Fetch version string
              run: echo "TAG=$(./src/pub/${{ matrix.asset-path }} --version | cut -c5- )" >> $GITHUB_ENV
              id: build_version
              shell: bash

            - run: printf '%s\n' "$TAG"

            - name: Rename output files
              run: mv src/pub/${{ matrix.asset-path }} TYM-${{ steps.build_version.outputs.TAG }}-${{ matrix.os }}

            #- name: Authorize Github CLI
            #  run: gh auth token ${{ secrets.G_TOKEN }}

            - name: Upload artifact
              run: gh release upload ${{ steps.build_version.outputs.TAG }} TYM-${{ steps.build_version.outputs.TAG }}-${{ matrix.os }}

            #- name: Upload artifact
            #  run: |
            #    curl -L \
            #      -X POST \
            #      -H "Accept: application/vnd.github+json" \
            #      -H "Authorization: Bearer ${{ secrets.G_TOKEN }}" \
            #      -H "X-GitHub-Api-Version: 2022-11-28" \
            #      -H "Content-Type: application/octet-stream" \
            #      "https://uploads.github.com/repos/${{github.repository}}/releases/${{ steps.build_version.outputs.TAG }}/assets?name=TYM-${{ steps.build_version.outputs.TAG }}-${{ matrix.os }}" \
            #      --data-binary "@src/pub/${{ matrix.asset-path }}"